

###
GET http://localhost:3000/api/users

###


GET http://localhost:3000/api/news

###
Get http://localhost:3000/api/users

###
GET http://localhost:3000/api/cities

###
GET http://localhost:3000/api/state

###

POST  http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Jude",
    "contact_phone": "6665889",
    "phone_verified": true,
    "email": "jude@gmail.com",
    "email_verified": true,
    "confirmation_code": "200",
    "password": "554554"
  }


###
DELETE  http://localhost:3000/api/users/1




# //state